// This file is generated by build-templates-index.ts
// Do not edit it manually
// Run `deno run --allow-read --allow-write build-templates-index.ts` to update it
//
export const root = "src/components"

export type TemplateFileName = 
  | "pageGlossary"
  | "itemSummaryBrowser"
  | "codeReference"
  | "contributeBlock"
  | "clipboardButton"
  | "carouselSlideContent"
  | "nodeFlashCard"
  | "clapsButton"
  | "downloadButtonsList"
  | "discordLetterInvite"
  | "promoGDSchool"
  | "itemSummaryBrowserHero"
  | "hint"
  | "pageGlossaryEntry"
  | "mainSearch"
  | "mailingListCollector"
  | "quoteBubble"
  | "calloutsList"
  | "videoEmbed"
  | "promoIntro"
  | "nodeFlashCardShuffler"
  | "checkpoint"
  | "pageTaxonomy"
  | "codeBlock"
  | "itemPageMeta"
  | "glossarySearch"
  | "fileInText"
  | "pageAuth"
  | "fontSizeResizer"
  | "scrollingList"
  | "itemSummaryCard"
  | "itemDiscordInvite"
  | "welcomeText"
  | "pageMain"
  | "openGraphTags"
  | "taxonomyPageHeader"
  | "glossarySeeAlsoBlock"
  | "collapsibleList"
  | "searchResultsGrid"
  | "exampleCallout"
  | "pageSearch"
  | "shareWidget"
  | "calloutItem"
  | "headerSiteSearch"
  | "gridItemsList"
  | "tableOfContents"
  | "collapsibleItem"
  | "carousel"
  | "pageItem"
  | "emailCampaign"
  | "itemCard"
  | "glossaryList"
  | "challenge"
  | "authForm"
  | "sectionTitle"
  | "footer"
  | "mainNav"
  | "calloutsListSingleItem"

export const templatesFiles = {
  pageGlossary: { 
    relPath: "pageGlossary/pageGlossary.vto",
    fullPath: "src/components/pageGlossary/pageGlossary.vto" 
  },
  itemSummaryBrowser: { 
    relPath: "itemSummaryBrowser/itemSummaryBrowser.vto",
    fullPath: "src/components/itemSummaryBrowser/itemSummaryBrowser.vto" 
  },
  codeReference: { 
    relPath: "codeReference/codeReference.vto",
    fullPath: "src/components/codeReference/codeReference.vto" 
  },
  contributeBlock: { 
    relPath: "contributeBlock/contributeBlock.vto",
    fullPath: "src/components/contributeBlock/contributeBlock.vto" 
  },
  clipboardButton: { 
    relPath: "clipboardButton/clipboardButton.vto",
    fullPath: "src/components/clipboardButton/clipboardButton.vto" 
  },
  carouselSlideContent: { 
    relPath: "carouselSlideContent/carouselSlideContent.vto",
    fullPath: "src/components/carouselSlideContent/carouselSlideContent.vto" 
  },
  nodeFlashCard: { 
    relPath: "nodeFlashCard/nodeFlashCard.vto",
    fullPath: "src/components/nodeFlashCard/nodeFlashCard.vto" 
  },
  clapsButton: { 
    relPath: "clapsButton/clapsButton.vto",
    fullPath: "src/components/clapsButton/clapsButton.vto" 
  },
  downloadButtonsList: { 
    relPath: "downloadButtonsList/downloadButtonsList.vto",
    fullPath: "src/components/downloadButtonsList/downloadButtonsList.vto" 
  },
  discordLetterInvite: { 
    relPath: "discordLetterInvite/discordLetterInvite.vto",
    fullPath: "src/components/discordLetterInvite/discordLetterInvite.vto" 
  },
  promoGDSchool: { 
    relPath: "promoGDSchool/promoGDSchool.vto",
    fullPath: "src/components/promoGDSchool/promoGDSchool.vto" 
  },
  itemSummaryBrowserHero: { 
    relPath: "itemSummaryBrowserHero/itemSummaryBrowserHero.vto",
    fullPath: "src/components/itemSummaryBrowserHero/itemSummaryBrowserHero.vto" 
  },
  hint: { 
    relPath: "hint/hint.vto",
    fullPath: "src/components/hint/hint.vto" 
  },
  pageGlossaryEntry: { 
    relPath: "pageGlossaryEntry/pageGlossaryEntry.vto",
    fullPath: "src/components/pageGlossaryEntry/pageGlossaryEntry.vto" 
  },
  mainSearch: { 
    relPath: "mainSearch/mainSearch.vto",
    fullPath: "src/components/mainSearch/mainSearch.vto" 
  },
  mailingListCollector: { 
    relPath: "mailingListCollector/mailingListCollector.vto",
    fullPath: "src/components/mailingListCollector/mailingListCollector.vto" 
  },
  quoteBubble: { 
    relPath: "quoteBubble/quoteBubble.vto",
    fullPath: "src/components/quoteBubble/quoteBubble.vto" 
  },
  calloutsList: { 
    relPath: "calloutsList/calloutsList.vto",
    fullPath: "src/components/calloutsList/calloutsList.vto" 
  },
  videoEmbed: { 
    relPath: "videoEmbed/videoEmbed.vto",
    fullPath: "src/components/videoEmbed/videoEmbed.vto" 
  },
  promoIntro: { 
    relPath: "promoIntro/promoIntro.vto",
    fullPath: "src/components/promoIntro/promoIntro.vto" 
  },
  nodeFlashCardShuffler: { 
    relPath: "nodeFlashCardShuffler/nodeFlashCardShuffler.vto",
    fullPath: "src/components/nodeFlashCardShuffler/nodeFlashCardShuffler.vto" 
  },
  checkpoint: { 
    relPath: "checkpoint/checkpoint.vto",
    fullPath: "src/components/checkpoint/checkpoint.vto" 
  },
  pageTaxonomy: { 
    relPath: "pageTaxonomy/pageTaxonomy.vto",
    fullPath: "src/components/pageTaxonomy/pageTaxonomy.vto" 
  },
  codeBlock: { 
    relPath: "codeBlock/codeBlock.vto",
    fullPath: "src/components/codeBlock/codeBlock.vto" 
  },
  itemPageMeta: { 
    relPath: "itemPageMeta/itemPageMeta.vto",
    fullPath: "src/components/itemPageMeta/itemPageMeta.vto" 
  },
  glossarySearch: { 
    relPath: "glossarySearch/glossarySearch.vto",
    fullPath: "src/components/glossarySearch/glossarySearch.vto" 
  },
  fileInText: { 
    relPath: "fileInText/fileInText.vto",
    fullPath: "src/components/fileInText/fileInText.vto" 
  },
  pageAuth: { 
    relPath: "pageAuth/pageAuth.vto",
    fullPath: "src/components/pageAuth/pageAuth.vto" 
  },
  fontSizeResizer: { 
    relPath: "fontSizeResizer/fontSizeResizer.vto",
    fullPath: "src/components/fontSizeResizer/fontSizeResizer.vto" 
  },
  scrollingList: { 
    relPath: "scrollingList/scrollingList.vto",
    fullPath: "src/components/scrollingList/scrollingList.vto" 
  },
  itemSummaryCard: { 
    relPath: "itemSummaryCard/itemSummaryCard.vto",
    fullPath: "src/components/itemSummaryCard/itemSummaryCard.vto" 
  },
  itemDiscordInvite: { 
    relPath: "itemDiscordInvite/itemDiscordInvite.vto",
    fullPath: "src/components/itemDiscordInvite/itemDiscordInvite.vto" 
  },
  welcomeText: { 
    relPath: "welcomeText/welcomeText.vto",
    fullPath: "src/components/welcomeText/welcomeText.vto" 
  },
  pageMain: { 
    relPath: "pageMain/pageMain.vto",
    fullPath: "src/components/pageMain/pageMain.vto" 
  },
  openGraphTags: { 
    relPath: "openGraphTags/openGraphTags.vto",
    fullPath: "src/components/openGraphTags/openGraphTags.vto" 
  },
  taxonomyPageHeader: { 
    relPath: "taxonomyPageHeader/taxonomyPageHeader.vto",
    fullPath: "src/components/taxonomyPageHeader/taxonomyPageHeader.vto" 
  },
  glossarySeeAlsoBlock: { 
    relPath: "glossarySeeAlsoBlock/glossarySeeAlsoBlock.vto",
    fullPath: "src/components/glossarySeeAlsoBlock/glossarySeeAlsoBlock.vto" 
  },
  collapsibleList: { 
    relPath: "collapsibleList/collapsibleList.vto",
    fullPath: "src/components/collapsibleList/collapsibleList.vto" 
  },
  searchResultsGrid: { 
    relPath: "searchResultsGrid/searchResultsGrid.vto",
    fullPath: "src/components/searchResultsGrid/searchResultsGrid.vto" 
  },
  exampleCallout: { 
    relPath: "exampleCallout/exampleCallout.vto",
    fullPath: "src/components/exampleCallout/exampleCallout.vto" 
  },
  pageSearch: { 
    relPath: "pageSearch/pageSearch.vto",
    fullPath: "src/components/pageSearch/pageSearch.vto" 
  },
  shareWidget: { 
    relPath: "shareWidget/shareWidget.vto",
    fullPath: "src/components/shareWidget/shareWidget.vto" 
  },
  calloutItem: { 
    relPath: "calloutItem/calloutItem.vto",
    fullPath: "src/components/calloutItem/calloutItem.vto" 
  },
  headerSiteSearch: { 
    relPath: "headerSiteSearch/headerSiteSearch.vto",
    fullPath: "src/components/headerSiteSearch/headerSiteSearch.vto" 
  },
  gridItemsList: { 
    relPath: "gridItemsList/gridItemsList.vto",
    fullPath: "src/components/gridItemsList/gridItemsList.vto" 
  },
  tableOfContents: { 
    relPath: "tableOfContents/tableOfContents.vto",
    fullPath: "src/components/tableOfContents/tableOfContents.vto" 
  },
  collapsibleItem: { 
    relPath: "collapsibleItem/collapsibleItem.vto",
    fullPath: "src/components/collapsibleItem/collapsibleItem.vto" 
  },
  carousel: { 
    relPath: "carousel/carousel.vto",
    fullPath: "src/components/carousel/carousel.vto" 
  },
  pageItem: { 
    relPath: "pageItem/pageItem.vto",
    fullPath: "src/components/pageItem/pageItem.vto" 
  },
  emailCampaign: { 
    relPath: "emailCampaign/emailCampaign.vto",
    fullPath: "src/components/emailCampaign/emailCampaign.vto" 
  },
  itemCard: { 
    relPath: "itemCard/itemCard.vto",
    fullPath: "src/components/itemCard/itemCard.vto" 
  },
  glossaryList: { 
    relPath: "glossaryList/glossaryList.vto",
    fullPath: "src/components/glossaryList/glossaryList.vto" 
  },
  challenge: { 
    relPath: "challenge/challenge.vto",
    fullPath: "src/components/challenge/challenge.vto" 
  },
  authForm: { 
    relPath: "authForm/authForm.vto",
    fullPath: "src/components/authForm/authForm.vto" 
  },
  sectionTitle: { 
    relPath: "sectionTitle/sectionTitle.vto",
    fullPath: "src/components/sectionTitle/sectionTitle.vto" 
  },
  footer: { 
    relPath: "footer/footer.vto",
    fullPath: "src/components/footer/footer.vto" 
  },
  mainNav: { 
    relPath: "mainNav/mainNav.vto",
    fullPath: "src/components/mainNav/mainNav.vto" 
  },
  calloutsListSingleItem: { 
    relPath: "calloutsListSingleItem/calloutsListSingleItem.vto",
    fullPath: "src/components/calloutsListSingleItem/calloutsListSingleItem.vto" 
  },
} satisfies Record<TemplateFileName, { relPath: string, fullPath: string }>
